p = [
    {"code_hasc": "DZ.AR",
     "name": "Adrar"},


    {"code_hasc": "DZ.AT",
     "name": "Aïn Témouchent"},
    {"code_hasc": "DZ.OR",
     "name": "Oran"},
    {"code_hasc": "DZ.SB",
     "name": "Sidi Bel Abbès"},
    {"code_hasc": "DZ.TL",
     "name": "Tlemcen"},
    {"code_hasc": "DZ.BC",
     "name": "Béchar"},
    {"code_hasc": "DZ.NA",
     "name": "Naâma"},
    {"code_hasc": "DZ.TN",
     "name": "Tindouf"},
    {"code_hasc": "DZ.AN",
     "name": "Annaba"},
    {"code_hasc": "DZ.ET",
     "name": "El Tarf"},
    {"code_hasc": "DZ.JJ",
     "name": "Jijel"},
    {"code_hasc": "DZ.SK",
     "name": "Skikda"},
    {"code_hasc": "DZ.IL",
     "name": "Illizi"},
    {"code_hasc": "DZ.TM",
     "name": "Tamanghasset"},
    {"code_hasc": "DZ.EB",
     "name": "El Bayadh"},
    {"code_hasc": "DZ.1950",
     "name": "El Oued"},
    {"code_hasc": "DZ.GR",
     "name": "Ghardaïa"},
    {"code_hasc": "DZ.LG",
     "name": "Laghouat"},
    {"code_hasc": "DZ.OG",
     "name": "Ouargla"},
    {"code_hasc": "DZ.AL",
     "name": "Alger"},
    {"code_hasc": "DZ.BM",
     "name": "Boumerdès"},
    {"code_hasc": "DZ.TO",
     "name": "Tizi Ouzou"},
    {"code_hasc": "DZ.TP",
     "name": "Tipaza"},
    {"code_hasc": "DZ.AD",
     "name": "Aïn Defla"},
    {"code_hasc": "DZ.CH",
     "name": "Chlef"},
    {"code_hasc": "DZ.MC",
     "name": "Mascara"},
    {"code_hasc": "DZ.MG",
     "name": "Mostaganem"},
    {"code_hasc": "DZ.RE",
     "name": "Relizane"},
    {"code_hasc": "DZ.SD",
     "name": "Saïda"},
    {"code_hasc": "DZ.TR",
     "name": "Tiaret"},
    {"code_hasc": "DZ.TS",
     "name": "Tissemsilt"},
    {"code_hasc": "DZ.BB",
     "name": "Bordj Bou Arréridj"},
    {"code_hasc": "DZ.BJ",
     "name": "Béjaïa"},
    {"code_hasc": "DZ.BL",
     "name": "Blida"},
    {"code_hasc": "DZ.BU",
     "name": "Bouira"},
    {"code_hasc": "DZ.BS",
     "name": "Biskra"},
    {"code_hasc": "DZ.DJ",
     "name": "Djelfa"},
    {"code_hasc": "DZ.MD",
     "name": "Médéa"},
    {"code_hasc": "DZ.MS",
     "name": "M'Sila"},
    {"code_hasc": "DZ.SF",
     "name": "Sétif"},
    {"code_hasc": "DZ.BT",
     "name": "Batna"},
    {"code_hasc": "DZ.CO",
     "name": "Constantine"},
    {"code_hasc": "DZ.GL",
     "name": "Guelma"},
    {"code_hasc": "DZ.KH",
     "name": "Khenchela"},
    {"code_hasc": "DZ.ML",
     "name": "Mila"},
    {"code_hasc": "DZ.OB",
     "name": "Oum el Bouaghi"},
    {"code_hasc": "DZ.SA",
     "name": "Souk Ahras"},
    {"code_hasc": "DZ.TB",
     "name": "Tébessa"}
]

wilaya = [
          {"01":"Adrar"},
          {"02": "Chlef"},
          {"03": "Laghouat"},
          {"04": "Oum El Bouaghi"},
          {"05": "Batna"},
          {"06": "Béjaïa"},
          {"07": "Biskra"},
          {"08": "Béchar"},
          {"09": "Blida"},
          {"10": "Bouira"},
          {"11": "Tamanrasset"},
          {"12": "Tébessa"},
          {"13": "Tlemcen"},
          {"14": "Tiaret"},
          {"15": "Tizi Ouzou"},
          {"16": "Alger"},
          {"17": "Djelfa"},
          {"18": "Jijel"},
          {"19": "Sétif"},
          {"20": "Saïda"},
          {"21": "Skikda"},
          {"22": "Sidi Bel Abbès"},
          {"23": "Annaba"},
          {"24": "Guelma"},
          {"25": "Constantine"},
          {"26": "Médéa"},
          {"27": "Mostaganem"},
          {"28": "M'Sila"},
          {"29": "Mascara"},
          {"30": "Ouargla"},
          {"31": "Oran"},
          {"32": "El Bayadh"},
          {"33": "Illizi"},
          {"34": "Bordj Bou Arreridj"},
          {"35": "Boumerdès"},
          {"36": "El Tarf"},
          {"37": "Tindouf"},
          {"38": "Tissemsilt"},
          {"39": "El Oued"},
          {"40": "Khenchela"},
          {"41": "Souk Ahras"},
          {"42": "Tipaza"},
          {"43": "Mila"},
          {"44": "Aïn Defla"},
          {"45": "Naâma"},
          {"46": "Aïn Témouchent"},
          {"47": "Ghardaïa"},
          {"48": "Relizane"}]

for item in wilaya:
    # print(list(item.values())[0])
    for i in p:
        if list(item.values())[0] == i["name"]:
            item["id"] = i["code_hasc"]

print(wilaya)

# hmdlh
done = [
 {'01': 'Adrar', 'id': 'DZ.AR'},
 {'02': 'Chlef', 'id': 'DZ.CH'},
 {'03': 'Laghouat', 'id': 'DZ.LG'},
 {'04': 'Oum El Bouaghi', 'id':'DZ.OB'},
 {'05': 'Batna', 'id': 'DZ.BT'},
 {'06': 'Béjaïa', 'id': 'DZ.BJ'},
 {'07': 'Biskra', 'id': 'DZ.BS'},
 {'08': 'Béchar', 'id': 'DZ.BC'},
 {'09': 'Blida', 'id': 'DZ.BL'},
 {'10': 'Bouira', 'id': 'DZ.BU'},
 {'11': 'Tamanrasset', 'id':'DZ.TM'},
 {'12': 'Tébessa', 'id': 'DZ.TB'},
 {'13': 'Tlemcen', 'id': 'DZ.TL'},
 {'14': 'Tiaret', 'id': 'DZ.TR'},
 {'15': 'Tizi Ouzou', 'id': 'DZ.TO'},
 {'16': 'Alger', 'id': 'DZ.AL'},
 {'17': 'Djelfa', 'id': 'DZ.DJ'},
 {'18': 'Jijel', 'id': 'DZ.JJ'},
 {'19': 'Sétif', 'id': 'DZ.SF'},
 {'20': 'Saïda', 'id': 'DZ.SD'},
 {'21': 'Skikda', 'id': 'DZ.SK'},
 {'22': 'Sidi Bel Abbès', 'id': 'DZ.SB'},
 {'23': 'Annaba', 'id': 'DZ.AN'},
 {'24': 'Guelma', 'id': 'DZ.GL'},
 {'25': 'Constantine', 'id': 'DZ.CO'},
 {'26': 'Médéa', 'id': 'DZ.MD'},
 {'27': 'Mostaganem', 'id': 'DZ.MG'},
 {'28': "M'Sila", 'id': 'DZ.MS'},
 {'29': 'Mascara', 'id': 'DZ.MC'},
 {'30': 'Ouargla', 'id': 'DZ.OG'},
 {'31': 'Oran', 'id': 'DZ.OR'},
 {'32': 'El Bayadh', 'id': 'DZ.EB'},
 {'33': 'Illizi', 'id': 'DZ.IL'},
 {'34': 'Bordj Bou Arreridj' , 'id' : "DZ.BB"},
 {'35': 'Boumerdès', 'id': 'DZ.BM'},
 {'36': 'El Tarf', 'id': 'DZ.ET'},
 {'37': 'Tindouf', 'id': 'DZ.TN'},
 {'38': 'Tissemsilt', 'id': 'DZ.TS'},
 {'39': 'El Oued', 'id': 'DZ.1950'},
 {'40': 'Khenchela', 'id': 'DZ.KH'},
 {'41': 'Souk Ahras', 'id': 'DZ.SA'},
 {'42': 'Tipaza', 'id': 'DZ.TP'},
 {'43': 'Mila', 'id': 'DZ.ML'},
 {'44': 'Aïn Defla', 'id': 'DZ.AD'},
 {'45': 'Naâma', 'id': 'DZ.NA'},
 {'46': 'Aïn Témouchent', 'id': 'DZ.AT'},
 {'47': 'Ghardaïa', 'id': 'DZ.GR'},
 {'48': 'Relizane', 'id': 'DZ.RE'}
]
